### ISSUE TITLE
ParadoxSitePlugin is missing while using sbt1.0 version

### ISSUE THREAD

**Issue by mushtaq** [sbt/sbt-site#112]
I do not see ParadoxSitePlugin on classpath while using sbt 1.0 while, for sbt 0.13.16 version, it is there. Am I missing something?

**Comment by jonas** [comment]
Yes, that's correct. Paradox was not cross compiled to sbt 1.0 until version 0.3.0 was released 11 hours ago. I've started working on supporting ParadoxSitePlugin for sbt 1.0 in #111 so 1.3.1 should be around the corner.

**Comment by mushtaq** [comment]
Perfect, thanks. For time being I copied the class.

**Comment by metasim** [comment]
Addressed by #111
