### ISSUE TITLE
previewSite exhibiting race condition on sub-projects

### ISSUE THREAD

**Issue by erikerlandson** [sbt/sbt-site#122]
I am running `sbt-site` on a repo having multiple sub-projects.  The `makeSite` target seems to be generating correctly but when I try to run `previewSite` (or previewAuto), the server seems to start serving one of the sub-projects, randomly, instead of the "root" project I defined to collect all the subproject output in.  As if it is trying to start the server on all subprojects and one is winning?

My build.sbt at the time of filing is:
https://github.com/erikerlandson/coulomb/blob/f8080dd6c7671034aa38aadd2b2769f52a978623/build.sbt

command would be `xsbt coulomb_docs/previewSite`

**Comment by jonas** [comment]
Sounds like you are running into #68. A workaround is to override the preview task in each subproject.

```
previewSite := {}
```

**Comment by erikerlandson** [comment]
that works, thanks!
