### ISSUE TITLE
Allow setting custom attributes for Asciidoctor

### ISSUE THREAD

**Issue by mhogerheijde** [sbt/sbt-site#156]
I'm using `front-matter` metadata in my files, to be able to upload our documentation to Confluence (using the [doktor Jenkins plugin](https://plugins.jenkins.io/doktor) ).

I _also_ want to have a `.zip` of our documentation and I want to use `previewSite` to be able to quickly see the effect of my changes.

`asciidoctor` can ignore the `front-matter` metadata, by passing an `attribute` with the value `skip-front-matter`.

Looking at the source-code, I can't see a way how I could set such an option from the `build.sbt`.

Could support for adding arbitrary `attributes` to the call to `asciidoctor` be added?

**Comment by ennru** [comment]
Yes, that would be great. Please suggest the necessary changes in a Pull Request.

**Comment by mhogerheijde** [comment]
I'm having trouble running the scripted tests and creating a test-set for this feature because I haven't installed all the binaries for all the documentation flavours. Is there a handy way to run a sub-set of the scripted tests?

**Comment by ennru** [comment]
You can use `sbt> scripted asciidoctor/asciidoctor-skips-frontmatter`.

**Comment by mhogerheijde** [comment]
Good to know!
