### ISSUE TITLE
Update to `scala-xml` 2.x

### ISSUE THREAD

**Issue by ckipp01** [sbt/sbt-site#179]
You can see the full conversation regarding this in https://github.com/sbt/sbt/discussions/7075, but the general idea is that since the new Scala 2.12.x series has updated to `scala-xml` 2.x and also sbt 1.8.x, then plugins should also update as well to not cause evictions errors with older versions of `scala-xml`, which this plugin brings in.

**Comment by ennru** [comment]
sbt-site needs more love than that. Moving to GH actions would be a good first step.

**Comment by ennru** [comment]
I spent some time getting some GH workflow up in #180.

**Comment by ennru** [comment]
Done with #201
