### ISSUE TITLE
Publish 1.5.0

### ISSUE THREAD

**Issue by julienrf** [sbt/sbt-site#209]
Hey, this is not really an issue but more of a discussion.

Do you have a timeline for publishing version 1.5.0?

I noticed that version 1.4.1 was published to the sbt community repository and I am currently figuring out which sbt plugins could be moved to Maven Central to reduce the load on the sbt community repository. I’ve noticed that the setup to publish to Maven Central is already in place, and that you’ve published 1.5.0-RC2 a few months ago. I would love to see the final 1.5.0 out there!

**Comment by ennru** [comment]
Thank you for the ping. I pushed the release button now:
- https://github.com/sbt/sbt-site/releases/tag/v1.5.0
