### ISSUE TITLE
site.settings configuration does not work as described

### ISSUE THREAD

**Issue by zoosky** [sbt/sbt-site#50]
//use sbt 0.13.8

site.settings

siteSourceDirectory <<= target / "generated-stuff" //defunct

siteMappings <++= Seq(file1 -> "location.html", file2 -> "image.png") //defunct

site.jekyllSupport() // works

**Comment by treyhyde** [comment]
yes, frustrating

**Comment by jsuereth** [comment]
which version of the site plugin are you using?

**Comment by treyhyde** [comment]
I am currently on 0.8.1

**Comment by sunchen115** [comment]
Can it generate site files for a folder containing html converted from Markdown files?

**Comment by jsuereth** [comment]
@sunchen115 should be able to, maybe ask on gitter.im/sbt/sbt?

**Comment by metasim** [comment]
@zoosky Please take a look at the upcoming 1.0 release:

https://github.com/sbt/sbt-site/tree/release/1.0.0-RC3
