### ISSUE TITLE
Support scaladoc for subprojects

### ISSUE THREAD

**Issue by dwalend** [sbt/sbt-site#55]
Putting site.includeScaladoc() in the top build file wasn't enough to get the scaladocs for the whole project included in site. 

Including sbt-site and the site.includeScaladoc() setting in subprojects gets the scaladoc into the zip file. However, that's not useful for putting together a zip file for the whole site.

Please add something to include subprojects' scaladocs via the top-level package-site command. I suspect each subproject should be able to include or exclude itself from the site, with everything included by default.  

Thanks,

Dave

**Comment by metasim** [comment]
_Note to contributors_: Need to create a `scripted` test for this scenario and see if it can be done with a combination of the [new autoplugin-based configuration](https://github.com/sbt/sbt-site/tree/release/1.0.0-RC3#scaladoc-apis) and [custom `Config` definitions](https://github.com/sbt/sbt-site/tree/release/1.0.0-RC3#advanced-usage).

**Comment by jonas** [comment]
@dwalend Did you consider using https://github.com/sbt/sbt-unidoc?

On a related note, we should add a test for using sbt-unidoc and maybe submit an to update its [example](https://github.com/sbt/sbt-unidoc#how-to-publish-scala-unidoc-to-github-pages). This is also a good use case for testing #60
