### ISSUE TITLE
Provide a search box for the current version of the documentation on the web site

### ISSUE THREAD

**Issue by mslinn** [sbt/sbt-site#64]
Here is the [HTML for Google](https://cse.google.com/cse/tools/create_onthefly):

````
<!-- Use of this code assumes agreement with the Google Custom Search Terms of Service. -->
<!-- The terms of service are available at http://www.google.com//cse/docs/tos.html -->
<form name="cse" id="searchbox_demo" action="https://www.google.com/cse">
  <input type="hidden" name="cref" value="" />
  <input type="hidden" name="ie" value="utf-8" />
  <input type="hidden" name="hl" value="" />
  <input name="q" type="text" size="40" />
  <input type="submit" name="sa" value="Search" />
</form>
<script type="text/javascript" src="https%3A%2F%2Fcse.google.com%2Fcse/tools/onthefly?form=searchbox_demo&lang="></script>
````

Here is a [link to a search form](https://www.google.com/advanced_search?as_sitesearch=http://scala-sbt.org/0.13/docs).

You could use duckduckgo or whatever, I don't care. The important thing is that the current version of the docs be searchable. The current state causes people to land on outdated documentation without realizing it.

**Comment by metasim** [comment]
@mslinn Are you suggesting this be added to the `sbt-site` plugin README.md file? Or is this issue really intended for https://github.com/sbt/website?

**Comment by mslinn** [comment]
I intended it for the web site

**Comment by metasim** [comment]
@mslinn I'd suggest filing the feature request there.
