### ISSUE TITLE
GitBook mappings include all dot files (e.g. `.git` and `.gitignore`)

### ISSUE THREAD

**Issue by metasim** [sbt/sbt-site#67]
If `sourceDirectory in GitBook` includes `.git`, `.gitbook`, etc. (as is the case when the manual is a git submodule), they get added to the `mappings in GitBook` setting and subsequently copied to the `target` directory.

**Comment by metasim** [comment]
@jonas Would you be willing to take this on?

**Comment by jonas** [comment]
Yes, please assign to me
