### ISSUE TITLE
jekyll plugin files filter

### ISSUE THREAD

**Issue by dzsessona** [sbt/sbt-site#69]
Is it possible to ovverride this key? 

includeFilter := ("*.html" | "*.png" | "*.js" | "*.css" | "*.gif" | "CNAME" | ".nojekyll"),

in

https://github.com/sbt/sbt-site/blob/master/src/main/scala/com/typesafe/sbt/site/jekyll/JekyllPlugin.scala

I have .ico, svg, .map and other files that the site needs, but the jekyll plugin filters out. I have already tried  preprocessIncludeFilter as per documentation but jekyll plugin ignores it.

**Comment by dzsessona** [comment]
At the moment my workaround is to specifically add those resources to the site as in this gist:

https://gist.github.com/dzsessona/90948d3e7119c9b57459cb2dcfcdfa03

But obviously opened to suggestions.

**Comment by metasim** [comment]
Can you try

```
 includeFilter in Jekyll :=  ("*.html" | "*.png" | "*.js" | "*.css" | "*.gif" | "CNAME" | ".nojekyll")
```

or 

```
 includeFilter in makeSite :=  ("*.html" | "*.png" | "*.js" | "*.css" | "*.gif" | "CNAME" | ".nojekyll")
```

to see if that helps? You were missing `*` in some of the globs, and you definitely need to specify a configuration axis.

**Comment by dzsessona** [comment]
@metasim Omg... how did I miss that. Thanks a lot for spotting it. It works, and btw with includeFilter in Jekyll .

Thanks again.
