### ISSUE TITLE
ParadoxSitePlugin appears to be incompatible with latest paradox release

### ISSUE THREAD

**Issue by sirthias** [sbt/sbt-site#75]
When running `sbt-site` version `1.1.0` with `sbt-paradox` version `0.2.3` and the default ("generic") paradox-theme no assets (JS/CSS) are produced to the `target/site` directory.

Seeing that the paradox support in `sbt-site` was built against `sbt-paradox 0.2.0` I'm assuming that some additional settings are now required to make paradox produce the theme assets in its output directory (so they can then be copied over to `target/site`).

An upgrade to `sbt-paradox` version `0.2.3` would be great!

**Comment by sirthias** [comment]
Note: When running against `sbt-paradox` version `0.2.2` everything works nicely. So the causing change on the paradox side must have been introduced between `0.2.2` and `0.2.3`.

**Comment by jonas** [comment]
This is more likely a regression in Paradox 0.2.3. See lightbend/paradox#30

**Comment by sirthias** [comment]
Ah, yes, right. I somehow missed that ticket.
Sorry for the noise!
