### ISSUE TITLE
Paradox setup guide needs attention

### ISSUE THREAD

**Issue by davesmith00000** [sbt/sbt-site#77]
Hi,

Spent a hour trying to work this out and thought I'd share. I'd do a PR but I still don't know if this is really right.

I had paradox running correctly. Decided to add the sbt ghpages plugin and that guide says "first setup sbt site". Ok, but being a so and so I've already add the ghpages stuff to build.sbt.

I'm using all the defaults taken straight from the setup guides so my build.sbt looks like this:

```
enablePlugins(ParadoxSitePlugin)

lazy val root = (project in file(".")).
  enablePlugins(ParadoxPlugin).
  settings(
    name := "My docs",
    paradoxTheme := Some(builtinParadoxTheme("generic"))
  )

ghpages.settings

git.remoteRepo := "git@github.com:<xxx>"
```

Hmmmm.... this does not work.

First it complains about a missing `siteSubdirName` value in the paradox settings. I've noticed (by googling, after many attempts at guessing the value - it's late here! :-) ) that a build has gone through where this defaults to empty string, so that's what I've done. Some sort of warning in the docs would have been good though.

Then it complains about an empty iterator with `paradoxMarkdownToHtml`. Turns out that paradox uses `src/main/paradox` by default while sbt site's paradox plugin expects `src/paradox`. Again, not obvious.

This seems to work:

```
enablePlugins(ParadoxSitePlugin)

sourceDirectory in Paradox := sourceDirectory.value / "main" / "paradox"

lazy val root = (project in file(".")).
  enablePlugins(ParadoxPlugin).
  settings(
    name := "My docs",
    siteSubdirName in Paradox := "",
    paradoxTheme := Some(builtinParadoxTheme("generic"))
  )

ghpages.settings

git.remoteRepo := "git@github.com:<xxx>"
```

Just needs a slight tweak to the docs please.

Cheers,

Dave

**Comment by jonas** [comment]
This issue has been fixed by @dwijnand in #74, which hasn't yet made it into a release.

**Comment by metasim** [comment]
@davesmith00000 Can you check release 1.2.0-RC1 and see if it addresses your issue?

**Comment by jonas** [comment]
I believe this can be closed.

**Comment by davesmith00000** [comment]
Sorry this took me a very long time to check, but yes the issue is resolved for me too.

**Comment by jonas** [comment]
Thank you for testing
