### ISSUE TITLE
Add Laika as site generator

### ISSUE THREAD

**Issue by vshalts** [sbt/sbt-site#92]
Hi,

there is pure Scala site generation engine - [Laika](https://github.com/planet42/Laika) It is quite interesting. I played with it and did my integration with sbt-site in [sbt-laika-blog](https://github.com/vshalts/sbt-laika-blog). Now I decided to go other way.

I realized that maybe it will better to merge that extension back to sbt-site, so it can be reused by others. If you are ready to support one more site generator then I can prepare PR for sbt-site (or you can do it your way). Does it make sense? Are you interested in PR for this site generator?

**Comment by metasim** [comment]
Hi @vshalts, thanks for offering to contribute your work. I've also played with Laika in the past, and thought it was a nice engine. Is it still being maintained?

As long as the addition has sufficient `scripted` tests, has sections in the documentation, and doesn't introduce dependencies that conflict with existing ones (and 2.12 versions are available), then it would be a strong candidate for inclusion. Let me know what you think.

**Comment by vshalts** [comment]
Hi @metasim, I am right now don't have access to internet for few weeks (travel :)  Meanwhile as far as I can tell Lakia doing slow progress and not dead. It compiled against the latest scala 2.11.8 and the latest updates were four month ago. I already have one scripted test, but can add more to make it good tested. I can write initial documentation, but somebody will need to review  it due I am not English native speaker and my English is no that good as I want it to be.

I am not sure why we need 2.12 for SBT plugin. From what I understand SBT right now use 2.10 internally. So plugin need Laika for 2.10 and that one exist and supported. On the other hand Laika have a lot of dependencies (to support pdf generation, etc). I am not sure this is good idea to enforce those dependencies for everybody when they don't need it.  Maybe we can use provided scope and ask users to to explicitly depend on Laika when that need it.

**Comment by metasim** [comment]
> I can write initial documentation, but somebody will need to review it due I am not English native speaker and my English is no that good as I want it to be.

Not a problem. We can take care of editing.

> I am not sure why we need 2.12 for SBT plugin. From what I understand SBT right now use 2.10 internally. 

You're right! I wasn't using my brain, and thinking about a different project (non-plugin) where we'd updated it recently to run on 2.12. Sorry about that!  :-)

**Comment by vshalts** [comment]
Ok then, I will do my best (expect some results after a month from now, due I am very busy right now)

**Comment by jonas** [comment]
Fixed by #95
